baseURL = "https://alcarney.me"
languageCode = "en-us"
title = "Alex Carney"

theme = "local"
disqusShortname = "alcarney-me"
enableEmoji = true

[markup.highlight]
style = "solarized-light"

[markup.goldmark.renderer]
unsafe = true  # Allow raw html in posts

[outputs]
home = ["HTML", "json"]

[params]
author = "Alex Carney"
description = "Software developer, amateur mathematician. I love to learn, try to animate and talk about it all to anyone who will listen"

[[params.social]]
name = "github"
url = "https://github.com/alcarney"

[[params.social]]
name = "twitter"
url = "https://twitter.com/alcarneyme"

[[params.social]]
name = "instagram"
url = "https://instagram.com/alcarneyme"

[[params.social]]
name = "youtube"
url = "https://www.youtube.com/channel/UC5GPflgRWhnCxA0BllfP5CA"

[[params.credits]]
name = "Feather Icons"
url = "https://github.com/feathericons/feather"