[context.production]
command = "./build.sh"

[context.production.environment]
HUGO_VERSION = "0.79.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "./build.sh"

[context.deploy-preview.environment]
HUGO_VERSION = "0.79.0"
