[project]
name = "alcarney.me"
version = "2026"
description = "My personal website"
requires-python=">=3.14"
dependencies = [
    "sphinx==8.2.*",
    "myst-parser==4.*",
    "rich @ git+https://github.com/alcarney/rich@fix-from-ansi",
    "awdur @ git+https://github.com/swyddfa/awdur@develop#subdirectory=lib/awdur",
]

[tool.esbonio.sphinx]
pythonCommand = ["uv", "run", "python"]
buildCommand = ["-M", "dirhtml", ".", "_build"]

