from __future__ import annotations

import pathlib
import typing
from functools import partial

from sphinx.builders.dirhtml import DirectoryHTMLBuilder
from sphinx.util.logging import getLogger

from .record import Record

if typing.TYPE_CHECKING:
    from typing import Any, Callable

    from .domain import Denote


logger = getLogger("denote")


def rewrite_indexed_docnames(*, freeze: Callable[[], dict[str, Any]]) -> dict[str, Any]:
    """Rewrite the docname in the search index so that they align to urls generated by
    the DenoteHTMLBuilder."""
    index = freeze()

    docnames = []
    for docname in index["docnames"]:
        if not docname.startswith("content/"):
            docnames.append(docname)
            continue

        if (record := Record.parse(docname.replace("content/", ""))) is None:
            docnames.append(docname)
            continue

        docnames.append(record.url)

    index["docnames"] = tuple(docnames)
    return index


class DenoteHTMLBuilder(DirectoryHTMLBuilder):
    """Translates documents with denote style filenames into something less crazy for
    the web"""

    def get_target_uri(self, docname: str, typ: str | None = None) -> str:
        domain: Denote = self.env.domains["denote"]

        if (record := domain.records.get(docname)) is None:
            return super().get_target_uri(docname, typ)

        result = super().get_target_uri(record.url, typ)
        return result

    def get_output_path(self, page_name: str) -> pathlib.Path:
        domain: Denote = self.env.domains["denote"]

        # Special case for the rss feed
        if page_name == "blog/atom":
            outpath = super().get_output_path(page_name)
            xml = str(outpath).replace("/index.html", ".xml")
            return pathlib.Path(xml)

        if (record := domain.records.get(page_name)) is None:
            return super().get_output_path(page_name)

        result = super().get_output_path(record.url)
        return result

    def dump_search_index(self):
        if (builder := self.indexer) is not None:
            builder.freeze = partial(rewrite_indexed_docnames, freeze=builder.freeze)

        super().dump_search_index()
