name: Blog

on:
  pull_request:
    branches:
    - release
  push:
    branches:
    - release

jobs:
  blog:
    name: Blog
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - name: Build
      uses: devcontainers/ci@v0.3
      with:
        cacheFrom: ghcr.io/alcarney/blog-devenv
        push: never
        runCmd: make html

    - name: 'Upload Aritfact'
      uses: 'actions/upload-artifact@v4'
      with:
        name: 'blog'
        path: '_build/dirhtml'

    - name: 'Publish Site'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: _build/dirhtml
        clean: true
      if: success() && startsWith(github.ref, 'refs/heads/release')
