name: Publish Blog

on:
  pull_request:
    branches:
    - release
    paths-ignore:
    - '.devcontainer/**'
  push:
    branches:
    - release
    paths-ignore:
    - '.devcontainer/**'

  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions: {}


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  #v10.0.1

    - run: make pages
      name: Build

    - name: 'Upload Aritfact'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: 'blog'
        path: '_build/blog.tar.gz'

  deploy:
    if: startsWith(github.ref, 'refs/heads/release')
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:

    - name: Publish
      id: deployment
      uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346  # v5.0.1
      with:
        artifact_name: blog
