name: Blog

on:
  pull_request:
    branches:
    - release
  push:
    branches:
    - release

jobs:
  blog:
    name: Blog
    runs-on: ubuntu-20.04
    steps:
    - uses: 'actions/checkout@v2'
      with:
        persist-credentials: false

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Setup Node
      uses: 'actions/setup-node@v1'
      with:
        node-version: 12.x

    - run: |
        set -e

        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

        npm install

      name: Setup Dependencies

    - run: |
        set -e
        make html
      name: Build

    - name: 'Upload Aritfact'
      uses: 'actions/upload-artifact@v1.0.0'
      with:
        name: 'blog'
        path: '_build/html'

    - name: 'Publish Docs'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _build/html
        CLEAN: true
      if: success() && startsWith(github.ref, 'refs/heads/release')