name: Blog

on:
  pull_request:
    branches:
    - release
  push:
    branches:
    - release

jobs:
  blog:
    name: Blog
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - uses: cachix/install-nix-action@v18

    - run: nix develop -c make html
      name: Build

    - name: 'Upload Aritfact'
      uses: 'actions/upload-artifact@v3'
      with:
        name: 'blog'
        path: '_build/html'

    - name: 'Publish Site'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: _build/html
        clean: true
      if: success() && startsWith(github.ref, 'refs/heads/release')
